package aula06.salaaula.endereco;

public enum TipoLogradouro {
    AEROPORTO, ALAMEDA, AREA, AVENIDA, CAMPO, CHACARA, COLONIA, CONDOMINIO, CONJUNTO,
    DISTRITO, ESPLANADA, ESTACAO, ESTRADA, FAVELA, FEIRA, JARDIM, LADEIRA, LAGO, LAGOA, LARGO,
    LOTEAMENTO, MORRO, NUCLEO, PARQUE, PASSARELA, PATIO, PRACA, QUADRA, RECANTO, RESIDENCIAL,
    RODOVIA, RUA, SETOR, SITIO, TRAVESSA, TRECHO, TREVO, VALE, VEREDA, VIA, VIADUTO, VIELA, VILA
}
