package aula06.salaaula.endereco;

public enum TipoLogradouro {
    AEROPORTO, ALAMEDA, AREA, AVENIDA, CAMPO, CHACARA, COLONIA, CONDOMINIO, CONJUNTO,
    DISTRITO, ESPLANADA, ESTAÇÃO, ESTRADA, FAVELA, FEIRA, JARDIM, LADEIRA, LAGO, LAGOA, LARGO,
    LOTEAMENTO, MORRO, NÚCLEO, PARQUE, PASSARELA, PÁTIO, PRAÇA, QUADRA, RECANTO, RESIDENCIAL,
    RODOVIA, RUA, SETOR, SÍTIO, TRAVESSA, TRECHO, TREVO, VALE, VEREDA, VIA, VIADUTO, VIELA, VILA
}
